services:
  postgres:
    image: postgres:15-alpine
    container_name: fly-lex-shop-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "${DB_PORT}:5433"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: fly-lex-shop
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
